### ISSUE TITLE
USB HS with R4

### ISSUE THREAD

**Issue by Jtonna** [skhrlx/skhrlx#1]
I saw your post about the HS with R4, and how you can get 1k polling with leonardo and not the r4.
I dont have a solution to your issue but have you considered writing a script to capture the peak number of reads vs writes to see where the issue actually is? You can also reach out to me on discord if youd like and i can see if i can help you >> notboosted

Also feel free to delete this issue after you read it

**Comment by skhrlx** [comment]
Thanks to be proactive, and sorry for my late response, but, I solved that here: https://github.com/arduino/ArduinoCore-renesas/pull/331
